CRITICAL - 2025-08-21 16:15:58 --> ErrorException: Undefined array key "notes"
[Method: GET, Route: appointments]
in APPPATH\Views\auth\appointments.php on line 51.
 1 APPPATH\Views\auth\appointments.php(51): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "notes"', 'C:\\xampp\\htdocs\\hms_group4\\app\\Views\\auth\\appointments.php', 51)
 2 SYSTEMPATH\View\View.php(226): include('C:\\xampp\\htdocs\\hms_group4\\app\\Views\\auth\\appointments.php')
 3 SYSTEMPATH\View\View.php(229): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1167): CodeIgniter\View\View->render('auth/appointments', [], true)
 5 APPPATH\Controllers\Appointments.php(19): view('auth/appointments', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Appointments->index()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Appointments))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-21 16:16:02 --> ErrorException: Undefined array key "notes"
[Method: GET, Route: appointments]
in APPPATH\Views\auth\appointments.php on line 51.
 1 APPPATH\Views\auth\appointments.php(51): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "notes"', 'C:\\xampp\\htdocs\\hms_group4\\app\\Views\\auth\\appointments.php', 51)
 2 SYSTEMPATH\View\View.php(226): include('C:\\xampp\\htdocs\\hms_group4\\app\\Views\\auth\\appointments.php')
 3 SYSTEMPATH\View\View.php(229): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1167): CodeIgniter\View\View->render('auth/appointments', [], true)
 5 APPPATH\Controllers\Appointments.php(19): view('auth/appointments', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Appointments->index()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Appointments))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-21 16:16:13 --> ErrorException: Undefined array key "notes"
[Method: GET, Route: appointments]
in APPPATH\Views\auth\appointments.php on line 51.
 1 APPPATH\Views\auth\appointments.php(51): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "notes"', 'C:\\xampp\\htdocs\\hms_group4\\app\\Views\\auth\\appointments.php', 51)
 2 SYSTEMPATH\View\View.php(226): include('C:\\xampp\\htdocs\\hms_group4\\app\\Views\\auth\\appointments.php')
 3 SYSTEMPATH\View\View.php(229): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1167): CodeIgniter\View\View->render('auth/appointments', [], true)
 5 APPPATH\Controllers\Appointments.php(19): view('auth/appointments', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Appointments->index()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Appointments))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-08-21 16:20:35 --> mysqli_sql_exception: Unknown column 'notes' in 'field list' in C:\xampp\htdocs\hms_group4\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\hms_group4\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `ap...', 0)
#1 C:\xampp\htdocs\hms_group4\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ap...')
#2 C:\xampp\htdocs\hms_group4\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ap...')
#3 C:\xampp\htdocs\hms_group4\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ap...', Array, false)
#4 C:\xampp\htdocs\hms_group4\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\hms_group4\system\BaseModel.php(838): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\hms_group4\system\Model.php(797): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\hms_group4\app\Controllers\Appointments.php(59): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\hms_group4\system\CodeIgniter.php(933): App\Controllers\Appointments->store()
#9 C:\xampp\htdocs\hms_group4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Appointments))
#10 C:\xampp\htdocs\hms_group4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\hms_group4\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\hms_group4\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp\htdocs\hms_group4\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2025-08-21 16:20:35 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'notes' in 'field list'
[Method: POST, Route: appointments/store]
in SYSTEMPATH\Database\BaseConnection.php on line 684.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `appointments` (`appointment_code`, `patient_name`, `patient_phone`, `doctor_name`, `date_time`, `type`, `status`, `notes`, `created_at`, `updated_at`) VALUES (:appointment_code:, :patient_name:, :patient_phone:, :doctor_name:, :date_time:, :type:, :status:, :notes:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\Appointments.php(59): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Appointments->store()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Appointments))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-21 16:20:35 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'notes' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `appointments` (`appointment_code`, `patient_name`, `patient_phone`, `doctor_name`, `date_time`, `type`, `status`, `notes`, `created_at`, `updated_at`) VALUES (\'03003\', \'yad\', \'efwfwf\', \'zyf\', \'2025-08-21 14:00\', \'Follow-up\', \'Confirmed\', NULL, \'2025-08-21 16:20:35\', \'2025-08-21 16:20:35\')')
 2 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `appointments` (`appointment_code`, `patient_name`, `patient_phone`, `doctor_name`, `date_time`, `type`, `status`, `notes`, `created_at`, `updated_at`) VALUES (\'03003\', \'yad\', \'efwfwf\', \'zyf\', \'2025-08-21 14:00\', \'Follow-up\', \'Confirmed\', NULL, \'2025-08-21 16:20:35\', \'2025-08-21 16:20:35\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `appointments` (`appointment_code`, `patient_name`, `patient_phone`, `doctor_name`, `date_time`, `type`, `status`, `notes`, `created_at`, `updated_at`) VALUES (:appointment_code:, :patient_name:, :patient_phone:, :doctor_name:, :date_time:, :type:, :status:, :notes:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\Appointments.php(59): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Appointments->store()
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Appointments))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-21 16:20:35 --> [Caused by] mysqli_sql_exception: Unknown column 'notes' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `appointments` (`appointment_code`, `patient_name`, `patient_phone`, `doctor_name`, `date_time`, `type`, `status`, `notes`, `created_at`, `updated_at`) VALUES (\'03003\', \'yad\', \'efwfwf\', \'zyf\', \'2025-08-21 14:00\', \'Follow-up\', \'Confirmed\', NULL, \'2025-08-21 16:20:35\', \'2025-08-21 16:20:35\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `appointments` (`appointment_code`, `patient_name`, `patient_phone`, `doctor_name`, `date_time`, `type`, `status`, `notes`, `created_at`, `updated_at`) VALUES (\'03003\', \'yad\', \'efwfwf\', \'zyf\', \'2025-08-21 14:00\', \'Follow-up\', \'Confirmed\', NULL, \'2025-08-21 16:20:35\', \'2025-08-21 16:20:35\')')
 3 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `appointments` (`appointment_code`, `patient_name`, `patient_phone`, `doctor_name`, `date_time`, `type`, `status`, `notes`, `created_at`, `updated_at`) VALUES (\'03003\', \'yad\', \'efwfwf\', \'zyf\', \'2025-08-21 14:00\', \'Follow-up\', \'Confirmed\', NULL, \'2025-08-21 16:20:35\', \'2025-08-21 16:20:35\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `appointments` (`appointment_code`, `patient_name`, `patient_phone`, `doctor_name`, `date_time`, `type`, `status`, `notes`, `created_at`, `updated_at`) VALUES (:appointment_code:, :patient_name:, :patient_phone:, :doctor_name:, :date_time:, :type:, :status:, :notes:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\Appointments.php(59): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Appointments->store()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Appointments))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
